apiVersion: apps/v1
kind: Deployment
metadata:
  name: matchmaking-service
  namespace: monopoly-game
  labels:
    app: matchmaking-service
    component: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: matchmaking-service
  template:
    metadata:
      labels:
        app: matchmaking-service
        component: backend
    spec:
      containers:
      - name: matchmaking-service
        image: jeffreyxu2025/monopoly-matchmaking:latest
        ports:
        - containerPort: 3003
        env:
        - name: PORT
          value: "3003"
        - name: REDIS_HOST
          value: "monopoly-dev-redis.f2xiko.ng.0001.usw2.cache.amazonaws.com"
        - name: REDIS_PORT
          value: "6379"
        - name: GAME_ENGINE_URL
          value: "http://game-engine-service:3001"
        - name: USER_SERVICE_URL
          value: "http://user-service:3002"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health/live
            port: 3003
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 3003
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: matchmaking-service
  namespace: monopoly-game
  labels:
    app: matchmaking-service
spec:
  selector:
    app: matchmaking-service
  ports:
  - port: 3003
    targetPort: 3003
    protocol: TCP
  type: ClusterIP
