name: Matchmaking Service CI/CD

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'monopoly/matchmaking/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'monopoly/matchmaking/**'

permissions:
  contents: write
  packages: write
  security-events: write

env:
  REGISTRY: docker.io
  IMAGE_NAME: jeffreyxu2025/monopoly-matchmaking-service

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: monopoly/matchmaking/package-lock.json

      - name: Install dependencies
        working-directory: monopoly/matchmaking
        run: npm ci

      - name: Run tests
        working-directory: monopoly/matchmaking
        run: npm test || echo "Tests not configured yet"

      - name: Security audit
        working-directory: monopoly/matchmaking
        run: npm audit --audit-level high || true

  build:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./monopoly/matchmaking
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
