name: Monopoly Game CI

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'monopoly/**'
      - '.github/workflows/monopoly-ci.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'monopoly/**'

# Add permissions for the workflow
permissions:
  contents: write
  packages: write
  security-events: write

env:
  REGISTRY: docker.io
  IMAGE_NAME: jeffreyxu2025/monopoly

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [game-engine, user-service, matchmaking, notification-service]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: monopoly/${{ matrix.service }}/package-lock.json

      - name: Install dependencies
        working-directory: monopoly/${{ matrix.service }}
        run: npm ci

      - name: Run tests
        working-directory: monopoly/${{ matrix.service }}
        run: npm test || echo "Tests not configured yet"

      - name: Security audit
        working-directory: monopoly/${{ matrix.service }}
        run: npm audit --audit-level high || true

  build:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    strategy:
      matrix:
        service: [game-engine, user-service, matchmaking, notification-service]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-${{ matrix.service }}
          tags: |
            type=ref,event=branch
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./monopoly/${{ matrix.service }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  update-manifests:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Update Kubernetes manifests
        run: |
          NEW_TAG="main-${{ github.sha }}"
          # Update all service images
          sed -i "s|image: jeffreyxu2025/monopoly-game-engine:.*|image: jeffreyxu2025/monopoly-game-engine:${NEW_TAG}|g" infra-dev/applications/main.tf
          sed -i "s|image: jeffreyxu2025/monopoly-user-service:.*|image: jeffreyxu2025/monopoly-user-service:${NEW_TAG}|g" infra-dev/applications/main.tf
          sed -i "s|image: jeffreyxu2025/monopoly-matchmaking-service:.*|image: jeffreyxu2025/monopoly-matchmaking-service:${NEW_TAG}|g" infra-dev/applications/main.tf
          sed -i "s|image: jeffreyxu2025/monopoly-notification-service:.*|image: jeffreyxu2025/monopoly-notification-service:${NEW_TAG}|g" infra-dev/applications/main.tf

      - name: Commit updated manifests
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add infra-dev/applications/main.tf
          
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "ci: Update image tags to main-${{ github.sha }} [skip ci]"
            git push
          fi
