name: Notification Service CI/CD

on:
  push:
    paths:
      - 'monopoly/notification-service/**'
      - 'infra-dev/services/notification-service/**'
  pull_request:
    paths:
      - 'monopoly/notification-service/**'
      - 'infra-dev/services/notification-service/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./monopoly/notification-service
        platforms: linux/amd64,linux/arm64
        push: true
        tags: jeffreyxu2025/monopoly-notification-service:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0
    
    - name: Deploy Notification Service
      run: |
        cd infra-dev/services/notification-service
        terraform init
        terraform plan
        terraform apply -auto-approve
